name: Update Domains

on:
  schedule:
    - cron: '0 22 * * *' # Every day at 22:00 UTC
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run updater
        id: runupd
        run: |
          python3 scripts/update_domains.py || echo "script exited with rc $?"

      - name: Detect changes
        run: |
          files="config/domains.json config/domains.jsonbk"
          if [ -f attenzione.check ]; then files="$files attenzione.check"; fi
          # Use -- to terminate pathspecs safely
          if git diff --quiet --exit-code -- $files; then
            echo "No changes to commit." >&2
            exit 0
          fi
          echo "changes=yes" >> $GITHUB_ENV

      - name: Commit changes
        if: env.changes == 'yes'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add config/domains.json config/domains.jsonbk || true
          if [ -f attenzione.check ]; then git add attenzione.check; fi
          git commit -m "fix: domains update" || echo "Nothing to commit"
          git push || echo "Push skipped"
